---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkeycluster-sample-conf
data:
  extra.conf: |
    maxmemory 50mb
    maxmemory-policy allkeys-lfu
  aof.conf: |
    appendonly yes
    appendfilename "orbit.aof"
